services:
  db:
    image: postgres:17.5-alpine3.22
    container_name: realstate_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data